version: '3'
services:
  worker0:
    build: .
    environment:
      - RANK=0
      - WORLD_SIZE=2
      - MASTER_ADDR=worker0
      - MASTER_PORT=12355
      - RUN_MODE=${RUN_MODE}
    networks:
      - distnet
  worker1:
    build: .
    environment:
      - RANK=1
      - WORLD_SIZE=2
      - MASTER_ADDR=worker0
      - MASTER_PORT=12355
      - RUN_MODE=${RUN_MODE}
    networks:
      - distnet
networks:
  distnet:
